proj1: proj1main.o proj1dbfunc.o 
	gcc -o proj1 proj1main.o proj1dbfunc.o

proj1main.o: proj1main.c
	gcc -c proj1main.c

proj1dbfunc.o: proj1dbfunc.c
	gcc -c proj1dbfunc.c

clean:
		rm proj1main.o proj1dbfunc.o proj1
