hw9: hw9main.o cat.o dog.o human.o animal.o
	g++ -o hw9 hw9main.o cat.o dog.o human.o animal.o

hw9main.o: hw9main.cpp 
	g++ -c hw9main.cpp

cat.o: cat.cpp
	g++ -c cat.cpp

dog.o: dog.cpp
	g++ -c dog.cpp

human.o: human.cpp
	g++ -c human.cpp

animal.o: animal.cpp
	g++ -c animal.cpp

clean:
	rm *.o hw9
