#! /bin/bash

rm test-image.png
echo "----------------------------------"
echo "Searching directory for file before transfer"
ls -lah | grep *.png
echo "----------------------------------"
echo
echo "Compiling"
make
echo "Compiling Finished"
echo "Listening..."
./client test-image.png
echo
echo "----------------------------------"
echo "Searching directory for file after transfer"
ls -lah | grep *.png
echo "----------------------------------"
echo
rm client server
